version: 2

jobs:
  test:
    docker:
      # Use crystallang/crystal:latest or specific crystallang/crystal:VERSION
      - image: crystallang/crystal:latest
    steps:
      - run: crystal --version
      - checkout
      - run: shards
      - run: crystal spec
  test-on-nightly:
    docker:
      - image: crystallang/crystal:nightly
    steps:
      - run: crystal --version
      - checkout
      - run: shards
      - run: crystal spec

workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-on-nightly
